# print("Введите вид животного:")
# vid = input()
# print("Введите кличку животного:")
# name = input()
# print("Введите возраст животного:")
# age = input()

# print('Это', vid, 'по кличке', '"',name,'".', 'Возраст:', age)

print('Введите этапы эволюции человека:')
a1 = input()
a2 = input()
a3 = input()
a4 = input()
a5 = input()
a6 = input()
print(a1, a2, a3, a4, a5, a6, sep= ' => ')